### ISSUE TITLE
CSVのインポート方法を確立する

### ISSUE THREAD

**Issue by yudaiogawa** [soften-works/playbook-earthquake-save-location#1]

**Comment by yudaiogawa** [comment]
### Download CSV file
* [鹿児島市ホームページ](https://www.city.kagoshima.lg.jp/jousys/opendata.html)よりオープンデータ取得．
* 今回は「[4-2 地震の退避場所](https://www.city.kagoshima.lg.jp/jousys/documents/4-2_jisinnjinotaihibasyo.csv)」をダウンロード．

**Comment by shomatan** [comment]
xPosition -> x_position  
yPosition -> y_position  
のほうがいいかもね

**Comment by yudaiogawa** [comment]
了解しました！

**Comment by shomatan** [comment]
インポートスクリプト完了。  
vagrant up 後、rootで`create-table`コマンドを実行するとテーブルが作成され、データをインポートする。

**Comment by shomatan** [comment]
Table schema: `places`  

|Name|Type|Nullable|Primary|
|:-----|:----|:--------|:------:|
|name|varchar(255)||○|
|address|varchar(255)|||
|position_x|double(10,5)|||
|position_y|double(10,4)|||
